settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  test_split_size: 0.05
  dataset_type: "preference"
  push_to_huggingface: true
  dataset_id: pauliusztin/llmtwin-dpo
  mock: false
